### PR TITLE
Enable REPL as a default MeTTa script inside Docker

### PR DESCRIPTION
**Pull request by vsbogd**
Enable REPL as a default MeTTa script inside Docker. Make a release build inside Docker by default.
NB: this Docker image contains temporary build files has big size and thus cannot be used as a MeTTa distribution package. If we want to distribute MeTTa as a Docker image it is better to improve this script or add another Dockerfile.

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
I don't have a strong opinion whether REPL should be the default MeTTa runner in Docker. I'm OK with this if this is a request from the Docker users.

**Comment by vsbogd** [comment]
> I don't have a strong opinion whether REPL should be the default MeTTa runner in Docker. I'm OK with this if this is a request from the Docker users.

It was not requested by the Docker users but one of the goals of adding REPL was to add additional flexibility to the MeTTa command line tool: syntax highlighting, step by step execution. Should we start using REPL by default?

**Comment by luketpeterson** [comment]
I don't have a strong opinion here either.  The REPL app has more capabilities than the Python runner (namely interactive mode)

Will https://github.com/trueagi-io/hyperon-experimental/issues/432 ever be issue or does the Docker environment mean this won't come up?  I think ie makes sense to merge it if the conda / pyenv issue is moot.

**Review by luketpeterson — APPROVED** [review]

**Comment by vsbogd** [comment]
> Will https://github.com/trueagi-io/hyperon-experimental/issues/432 ever be issue or does the Docker environment mean this won't come up? I think ie makes sense to merge it if the conda / pyenv problem is a non-issue.

It will not be a problem inside a Docker container because global Python environment is used.

**Comment by vsbogd** [comment]
Replaced by #732

**Pull request closed without merging**
