### PR TITLE
Fix unique

### LINKED ISSUE #760: Subtraction, union, intersection and unique doesn't work after switching to minimal MeTTa
**Describe the bug**

`subtraction`, `union`, `intersection` and `unique` doesn't work after switching to minimal MeTTa:

**To Reproduce**
1. run `!(subtraction (superpose (a b d)) (intersection (superpose (a b c)) (superpose (a b d))))`

**Expected behavior**
Result is `[d]`

**Actual behavior**
Result is `[d, b, a]`

**Additional context**
 - `metta-repl 0.2.0`

### PR DESCRIPTION
**Pull request by vsbogd**
Fixes #760 
Also removes interpreter from the functions implementations.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Works like a charm, thanks!

**Review by ngeiswei — DISMISSED** [review]

**Comment by ngeiswei** [comment]
Unfortunately I spoke too fast :-(, it does not work in my case, but it is a complex one, I want to simplify it a bunch before pasting it here.  But to give you an idea, the following
```scheme
!(unique (bc &kb
             (fromNumber 5)
             (: $prg (-> (: $x (SongIn "English")) (SongIn "Chinese")))))
```
does not work, while the following
```
!(let* (($results (collapse
                   (bc &kb
                       (fromNumber 5)
                       (: $prg (-> (: $x (SongIn "English")) (SongIn "Chinese"))))))
        ($uniq-results (unique (superpose $results))))
   $uniq-results)
```
does.  Meaning that I need to explicitly collapse the results, then call `unique` on their superposition, and then it works.

I am not sure if it is a bug or a feature, I can still use that, but of course it is not as elegant as just calling `unique` on my non-deterministic function call.

**Comment by ngeiswei** [comment]
Please find a simplified example
```scheme
(= (f) a)
(= (f) a)

!(unique (f))
!(let $y (collapse (f)) (unique (superpose $y)))
```

**Comment by vsbogd** [comment]
Thanks @ngeiswei. Seems like it is a bug which prevented me to implement it last time. `unique` is implemented in stdlib and thus when `collapse` is called from implementation it uses `stdlib` space as a context. As consequence `(f)` is not evaluated and stays `(f)` because stdlib doesn't have definition of `(f)`. It is the reason why `unique` returns `(f)` and after collapse it is evaluated in two instances of `a`.

**Comment by vsbogd** [comment]
Well, I think we can merge it, because it is better then previous state. Then I will think how to fix it properly and raise another PR.

**Review by ngeiswei — APPROVED** [review]

**Comment by vsbogd** [comment]
Btw, @ngeiswei , the following code works:
```
(= (f) a)
(= (f) a)

!(unique (capture (f)))
```

**Pull request merged**
