### PR TITLE
modify == to handle symbolic expressions

### PR DESCRIPTION
**Pull request by Necr0x0Der**

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
I've changed `==` implementation to handle symbolic expressions. The reason is that it is difficult to implement `eq` in pure MeTTa to return `False`, while it is needed in practice. The downside is that `==` behaves differently from, say, `<` or `>` in that it will not remain unreduced if its arguments are not reduced. It will always return `True` or `False`. This behavior makes sense, but it may cause some confusion.

**Review by vsbogd — APPROVED** [review]

**Comment by ngeiswei** [comment]
Thanks @Necr0x0Der, that's quite useful.

I think supporting `<` and `>` for any expression could also be useful, for instance to define a sorted list of expressions, but that can probably be done in pure MeTTa.  Or, to be maximally useful, it would probably need to be overwritable for handling cases where expressions require their own order, such as `(: Z Nat), (: S (-> Nat Nat))`, etc.

**Comment by Necr0x0Der** [comment]
@ngeiswei , well, I had a thought on this. The problem is that `==` returning always `True` or `False` makes some sense (e.g., even if its arguments are of different type, then the result is just `False`). At the same time, `<` or `>` should not always return `True` or `False`. Well, with `(-> $t $t Bool)` type signature, the case of different argument types can be handled (as a typing error), but still even for the same `$t`, binary comparison operators will not always make sense. (well, I agree that equality relations are not necessarily binary as well, but order-related comparisons are way much choosy). Thus, "supporting `<` and `>` for any expression` seems questionable to me, they "needed to be overridable" sounds right. The latter is exactly a usecase for #147

**Comment by ngeiswei** [comment]
I wonder if we could have a "syntactic less than" as we do in Atomese.  It wouldn't need to use the `<` character though.

**Comment by Necr0x0Der** [comment]
@ngeiswei , could you please elaborate on this? I'm not sure what "syntactic less than" means.

**Comment by ngeiswei** [comment]
@Necr0x0Der, specifically I mean

https://github.com/opencog/atomspace/blob/1fd6118ecfd0a4781cd3bb765ca521b03aaf719e/opencog/atoms/base/Atom.h#L534

implemented here

https://github.com/opencog/atomspace/blob/1fd6118ecfd0a4781cd3bb765ca521b03aaf719e/opencog/atoms/base/Node.cc#L116-L131
https://github.com/opencog/atomspace/blob/1fd6118ecfd0a4781cd3bb765ca521b03aaf719e/opencog/atoms/base/Link.cc#L130-L165

and else where.

Well, this one is more than just "syntactic order".  First it compares the hash keys, and only resort to "syntactic order" if the keys are the same.  I'm sure there's a colloquial term for it but I don't know it, it might be something like "prefix tree lexicographic order", or such.

**Comment by Necr0x0Der** [comment]
> I wonder if we could have a "syntactic less than" as we do in Atomese. It wouldn't need to use the `<` character though.

> First it compares the hash keys, and only resorts to "syntactic order" if the keys are the same. 

After Vitaly introduced indexing, something similar might be possible to implement. However, I wonder if it would be correct to have this comparison dependent on the way of how indexing is done. Or should it be invariant? Maybe, knowing the purpose of "syntactic less than" would be useful.

**Comment by ngeiswei** [comment]
A potential use of a "syntactic less than" operator would be if we want to write an algorithm in metta (or python or even rust) code that needs an ordered set or an order map of atoms, for instance.

**Pull request merged**
