### PR TITLE
Ensure GitHub actions are executed with minimal supported Python version 3.7

### PR DESCRIPTION
**Pull request by vsbogd**
Python version 3.6 is not supported by the actual GitHub actions runners. The oldest runner is `ubuntu-20.04` and the oldest Python version is 3.7.

Makefiles still support 3.6 or later but this support is done on the best effort basis. Guarantees are given for the Python 3.7 and later.

### CODE REVIEW

**Comment by vsbogd** [comment]
I am not sure does it makes sense to support 3.6? May be we should switch to the 3.8 or later.
From the common sense I feel it is better to support for 3.6 in order to support Ubuntu 18.04 users.

**Comment by vsbogd** [comment]
Tried to run Python 3.6 using `pyenv` but it doesn't work for me.

**Comment by Necr0x0Der** [comment]
> Tried to run Python 3.6 using `pyenv` but it doesn't work for me.

Maybe we can "officially" abandon support of Python 3.6 then

**Comment by vsbogd** [comment]
Yes, it what I am proposing. Support 3.6 on a best effort basis.
As an alternative somebody can help with using Python 3.6 inside GitHub actions script.

**Review by ngeiswei — APPROVED** [review]
I don't know well enough github ci to help unfortunately.

**Comment by noskill** [comment]
it's reasonable to switch to python 3.7, it's already around 5 years old

**Review by noskill — APPROVED** [review]

**Pull request merged**
