### PR TITLE
Fix nested variable operations

### PR DESCRIPTION
**Pull request by vsbogd**
Quick fix for #642

### CODE REVIEW

**Review by ngeiswei — CHANGES_REQUESTED** [review]
Running

```
(= ((W $x) $y) (($x $y) $y))
!(($x $y) $y)
```

outputs

```
[(($x $y) $y), (($x $y) $y)]
```

instead of

```
[(($x $y) $y)]
```

Is it normal?

**Comment by vsbogd** [comment]
Thanks for checking Nil, I am sorry for that. It is not normal and this happens because tuples of variables are matched with random types. In this case `($x $y)` tuple matches with `(: (@kind atom) ...)` and (: (@kind function) ...)` type, which causes two different interpretation to be returned.

**Comment by vsbogd** [comment]
The effect above is raised as issue #235

**Review by ngeiswei — APPROVED** [review]

**Comment by vsbogd** [comment]
I don't want to merge it now, I would like to finish discussion in #642 first. Please see possible solution https://github.com/trueagi-io/hyperon-experimental/issues/642#issuecomment-2061567989

**Comment by vsbogd** [comment]
@ngeiswei , should be fixed now, please try it.

**Comment by ngeiswei** [comment]
With the latest revision 23a22d28

```
(= ((W $x) $y) (($x $y) $y))
!(($x $y) $y)
```

still spawns MeTTa in a infinite recursion (with `variable_operation` disabled).

**Comment by ngeiswei** [comment]
Oh, these are new commits, let me check then!

**Comment by ngeiswei** [comment]
It behaves as expected on my end.

**Review by ngeiswei — APPROVED** [review]

**Comment by ngeiswei** [comment]
It's awesome to see these old issues being knocked down one by one!  Thanks!

**Pull request merged**
