### PR TITLE
Minimal interpreter: adding function/return and fix most of the tests

### PR DESCRIPTION
**Pull request by vsbogd**
Improving semantics of minimal MeTTa `chain` to make code more predictable. I didn't change the documentation yet because I am going to experiment with `eval/chain/return` further and then finalize the semantics. After adding `function/return` I managed to write MeTTa interpreter in minimal MeTTa which now passes almost all of the tests except:
- Minecraft related tests
- one test in minimal MeTTa Rust test pack
- `f1_import` test

List of changes:
Implement `function` and `return` symbols to allow coding function call flows. Make `chain` one-step operation, i.e. `chain` makes one step and inserts the result into a provided template. One can make `chain` work in a loop by: 
- using nested `chain`, then `chain` waits while nested `chain` returns result
- using nested `function`, then `chain` waits for a `function` to return result
Thus nested `chain` + `function` expressions represent the call stack of the program.

Import `pragma!`, `bind!`, space operations, state operations from stdlib to stdlib of minimal MeTTa.
Implement `case`, `quote/unquote`, `id`, `car-atom`, `cdr-atom`, `or`, `and`, `fold`, `filter` and `map` in minimal MeTTa.
Change `get-type` implementation to be compatible with both Rust and minimal MeTTa interpreters.
Fix type casting issue when type errors were returned for non-deterministic types when one of the types was not compatible with required type.
Fix `test_examples.py` to be compatible with minimal MeTTa standard library.
Adapt "returning unit" from grounded functions fix from `main` branch.

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
I'd like to migrate to minimal metta asap, so I'm worried only about tests and performance, but not internals. Thus, I'm happy to approve this PR. A few remarks, which should not be considered within this PR:

* I'm definitely ok with `(Error Z BadType)` changing to `(Error (Cons Z Nil) BadType)`, which is more informative. But I'd either turn the whole assert off with a proper comment, or make the test work in both cases, e.g. checking for `Error` or `BadType` only if it is not cumbersome. Maybe, we can introduce `assertMatchable` and check for `(Error $_ BadType)` if it makes sense.

* I'm ok with moving test_minecraft and test_minology from obligatory tests (to integration tests?). But it might be useful to figure out the problem with test_minecrat and see if it is important (possibly, add a clean unit test if appropriate). The problem with minology is that `BadType` is returned among the correct answers. It's definitely the change in semantics. Previously, BadType was returned when there were no valid alternatives only. Now, it is returned among valid alternatives as well. This makes some sense, but may make the use of non-deterministic types cumbersome. This requires more detailed analysis, which can be postponed, but not ignored. Thus, moving minology to integration tests is ok.

* I'm ok with modifying `test_frog_reasoning` test, but am a little bit sad that the first element of tuples gains even more uniquness.

* I see a lot of code in stdlib.metta, and start wondering if we will introduce local caches in the future (e.g. like `__pycache__`) to load it and other modules faster. Do you think it worths mentioning in #470 or is it a very separate issue?

* stdlib.metta contains a lot of functions with a little bit questionable names, e.g. `filter`, `map`, etc., which are too typical and can cause some name conflicts, e.g. we may want to have these functions on `List` type instead of atoms. But this can be discussed later.

**Review by Necr0x0Der — APPROVED** [review]

**Comment by vsbogd** [comment]
> I'm definitely ok with (Error Z BadType) changing to (Error (Cons Z Nil) BadType), which is more informative. But I'd either turn the whole assert off with a proper comment, or make the test work in both cases, e.g. checking for Error or BadType only if it is not cumbersome. Maybe, we can introduce assertMatchable and check for (Error $_ BadType) if it makes sense.

Do you mean turn it off for both minimal and old interpreter? I would prefer doing this instead of adding `assertMatchable` for this only case. 

> The problem with minology is that BadType is returned among the correct answers. It's definitely the change in semantics.

Yes, it is one more place for the type-checking logic to fix in minimal interpreter. I will fix it.

> I'm ok with modifying test_frog_reasoning test, but am a little bit sad that the first element of tuples gains even more uniquness.

Not sure I understand you properly. The problem is the same which is described in #242. As standard library has more functions now, the code of the test matches them. It would happen even with old interpreter if we add new functions into stdlib.

> I see a lot of code in stdlib.metta, and start wondering if we will introduce local caches in the future (e.g. like __pycache__) to load it and other modules faster. 

Do you mean we need to pre-compile MeTTa libraries? It makes sense but I would make it a separate issue from a package management because its complexity is in precompilation not in aligning it with packaging system.

> stdlib.metta contains a lot of functions with a little bit questionable names, e.g. filter, map, etc., which are too typical and can cause some name conflicts, e.g. we may want to have these functions on List type instead of atoms. But this can be discussed later.

Since minimal MeTTa I am writing more code in MeTTa and more frequently facing name conflicts. I can assign unique names for the functions in standard library for sure but namespaces would be really useful here (I believe they are already mentioned in #470)

**Comment by Necr0x0Der** [comment]
> Do you mean turn it off for both minimal and old interpreter? I would prefer doing this instead of adding assertMatchable for this only case.

Yes, to avoid switching back and forth between two versions of the test until we completely migrate to Minimal MeTTa, when we can turn it on back.

> It would happen even with old interpreter if we add new functions into stdlib.

OK, I see.

> Do you mean we need to pre-compile MeTTa libraries?

Pre-compilation is the next step. At first, we can just store parsed spaces in files (for which they should be serializable). But yes, it seems like a separate branch of development. And maybe it (saving on parsing) is really a minor thing, and it will start to be interesting only after pre-compilation, which is really a very separate story.

>  but namespaces would be really useful here

I supposed that stuff from stdlib will not be in a separate namespace to avoid, e.g. `stdlib::if`. But maybe we can import such stuff as `if` directly to the main script namespace, while `map` can remain in stdlib namespace. But I mean that `map` for `List` can also be in stdlib. In any case, I pointed out to the question of naming such widely used but differently implemented functions (e.g. `map-atom` similar to `car-atom`?) just to not forget discuss it later.

**Comment by Necr0x0Der** [comment]
I'm ok with renaming `map` -> `map-atom` right away, but it makes the further review of naming less relevant :)

**Comment by vsbogd** [comment]
> Yes, to avoid switching back and forth between two versions of the test until we completely migrate to Minimal MeTTa, when we can turn it on back.

Fixed in https://github.com/trueagi-io/hyperon-experimental/pull/472/commits/1646df9236bf71e1e65f43a80c05a40d16917990

> I supposed that stuff from stdlib will not be in a separate namespace to avoid

Yes, ok, probably namespaces are not so useful for the functions we are going to export from the stdlib, but we can use them to make functions private, in particular some implementation specific stdlib functions. But yes maybe it is not so important, we always can add prefix stdlib for them.

**Review by Necr0x0Der — APPROVED** [review]

**Pull request merged**
