### PR TITLE
Minimal interpreter performance fixes

### PR DESCRIPTION
**Pull request by vsbogd**
Use stack to represent state of the interpreter and eliminate atom deconstructing/constructing on each step. Make small performance related fixes in the interpreter written in MeTTa.

### CODE REVIEW

**Review by luketpeterson — COMMENTED** [review]
This is a huge performance win on my setup.  :-)

**Comment by luketpeterson** [comment]
One of the tests hits this error, however.
```
 5/16 Test  #5: test_examples.py .................***Failed   16.33 sec
.......Fs.
======================================================================
FAIL: test_plus_reduces_Z (test_examples.ExamplesTest.test_plus_reduces_Z)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/admin/rustProjects/hyperon-experimental/python/tests/test_examples.py", line 146, in test_plus_reduces_Z
    self.assertAtomsAreEquivalent(output[0], metta.parse_all('(eq (S $y) $y)'))
  File "/Users/admin/rustProjects/hyperon-experimental/python/tests/test_common.py", line 58, in assertAtomsAreEquivalent
    self.assertTrue(atoms_are_equivalent(actual, expected),
AssertionError: False is not true : Lists of atoms are not equivalent. First pair of different atoms:
- True
+ (eq (S $y) $y)
```

**Review by luketpeterson — APPROVED** [review]
These changes all look like they move in the right direction.

**Review by Necr0x0Der — APPROVED** [review]

**Comment by vsbogd** [comment]
> One of the tests hits this error, however. (minimal)

Yes, looks like new implementation has floating error in variable bindings processing. It passes on my hardware but I see one test is failed on CI and another is posted by you. Will look at it.

**Comment by vsbogd** [comment]
I am merging it to unblock documentation PR. I will raise a separate PR to fix the unstable unit test results.

**Pull request merged**
