### PR TITLE
example of a space which query calls gpt-3.5

### PR DESCRIPTION
**Pull request by Necr0x0Der**

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
@astroseger , fyi

**Review by luketpeterson — APPROVED** [review]
This is very cool as a demonstration of the flexibility of MeTTa!

I don't have much to say about how you're using the API.  That looks good.  I do have some other questions / comments:

1. This comment is more about my own ignorance / lack of visibility into the MeTTa vision, but I am unclear why the GPT interface is implemented as a Space, rather than just inside a Grounded Atom (without the Space)?  I see the way the space's "container-like" property is useful for storing information.  And also how a language model can be conceptually thought of as encompassing a knowledge-base.  However this space couldn't be queried with arbitrarily complex expression atoms to match, which I thought was a conceptual requirement for the Space interface.

2. This is a great demonstration as it is.  But in my experience some more robustness in output parsing is needed if one wanted to productize this.  GPT can sometimes provide unexpected characters (e.g. punctuation, etc.)  However, if this is intended as a demo then parsing robustness code would get in the way so maybe it's best to leave it the way you have it.

3. I feel like the name "neurospace" might not be totally accurate.  Is it better to call it "lmspace" or "gptspace", given we might try and implement other NN algorithms within MeTTa in the future?

4. This is unrelted, but the repl (the one I wrote in Rust) doesn't support the `extend-py!` atom.  So that's something I need to figure out how to handle.

**Comment by vsbogd** [comment]
> 4. This is unrelated, but the repl (the one I wrote in Rust) doesn't support the extend-py! atom. So that's something I need to figure out how to handle.

I believe here we could agree that Python and Rust can have specific parts of the stdlib which can be used only from Python REPL or Rust REPL respectively. At least until we have a good solution for https://github.com/trueagi-io/hyperon-experimental/issues/351

**Comment by Necr0x0Der** [comment]
> 1. This comment is more about my own ignorance / lack of visibility into the MeTTa vision, but I am unclear why the GPT interface is implemented as a Space, rather than just inside a Grounded Atom (without the Space)?

Yeah, I also wondered what is the difference between atoms and spaces. Apparently, spaces respect certain API, and if we redefine `query` instead of `match`, it would be a space. But of course, it can be done via a grounded atom and corresponding grounded query function as well. But any space can be implemented as a grounded atom. So, why do we need Space API at all? This example is intended to show the use of Space API and it supposes further extensions or alternative implementations, e.g. storing additional embeddings of MeTTa expressions, or history of LLM prompts as a part of space extension, or whatever.

> 2. But in my experience some more robustness in output parsing is needed if one wanted to productize this. 

Of course. This is just an example in the sandbox. You should not expect it to be product-ready. If we will work on LLM-MeTTa integration framework, the code will be much more sophisticated.

> 3. I feel like the name "neurospace" might not be totally accurate.  Is it better to call it "lmspace" or "gptspace", given we might try and implement other NN algorithms within MeTTa in the future?

Yes, this example doesn't precisely correspond to "neurospace", and maybe it should have a different name if it would be a stand-alone demonstration. The reason for this name is that we discussed a possibility to create a neural space, which could be based on differentiable embeddings of MeTTa code with graph transformers or something else for queries. And this code is supposed as a maximally simplistic demonstration of using DNNs for querying a space (although without "neurospace" per se).

> 4. This is unrelted, but the repl (the one I wrote in Rust) doesn't support the `extend-py!` atom.  So that's something I need to figure out how to handle.

Well, as we (hopefully) discussed, there should be a common part of REPL implemented in Rust, and REPLs themselves implemented in Rust and Python. While REPL in Rust should not necessarily support `extend-py!`, REPL in Python should.

**Pull request merged**
