### PR TITLE
fetch support added to dasgate.py

### PR DESCRIPTION
**Pull request by CICS-Oleg**

### CODE REVIEW

**Review by Starfox86isme — APPROVED** [review]

**Review by DaddyWesker — APPROVED** [review]
Both test_das and test_bio_das works for me.

**Comment by Necr0x0Der** [comment]
Is it still draft?

**Comment by CICS-Oleg** [comment]
> Is it still draft?

Yep, there is one problem on my side. I want @DaddyWesker to check this on his side.

**Comment by DaddyWesker** [comment]
Both tests are still works for me. Though it takes ~ 4 minutes for test_bio_das to finish.

**Pull request merged**
