### PR TITLE
Move docker environment instructions to the top of the README.md

### PR DESCRIPTION
**Pull request by vsbogd**

### CODE REVIEW

**Comment by vsbogd** [comment]
Looks like docker image doesn't work anymore :-)

**Comment by vsbogd** [comment]
@noskill , could you please double check instruction works to you?

**Comment by noskill** [comment]
@vsbogd yes it is brocken:

```
ERROR: pybind11/2.7.1: Error in package_id() method, line 66
        self.info.clear()
        AttributeError: 'ConanInfo' object has no attribute 'clear'
CMake Error at python/CMakeLists.txt:6 (include):
  include could not find requested file:
    /home/user/hyperon-experimental/build/python/conan_paths.cmake


CMake Error at python/CMakeLists.txt:7 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by vsbogd** [comment]
Have you upgraded the `Conan` version to 1.50?

**Comment by noskill** [comment]
yes, instruction is broken for old dockerfile and works for the one from this pr

**Comment by vsbogd** [comment]
Please, approve then :-)

**Review by noskill — APPROVED** [review]

**Pull request merged**
